config/routes.rb
SampleApp::Application.routes.draw do

  root 'static_pages#home'
  match '/resume',    to: 'static_pages#resume',    via: 'get'
  match '/projects',   to: 'static_pages#projects',   via: 'get'
  match '/interactive_resume',    to: 'static_pages#interactive_resume',   via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def resume
  end

  def projects
  end

  def interactive_resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Alan Daniels"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<%= link_to image_tag("linkedin.png", alt: "Rails"), 'https://ca.linkedin.com/in/alan-daniels-26560898' %>
	</small>
	<nav>
		<ul>
			alan.daniels@mail.utoronto.ca
		</ui>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Alan Daniels", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home",		root_path %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Resume<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to "Animated Resume",	interactive_resume_path %></li>
							<li><a href="/AlanDaniels_Resume.pdf">Professional Resume (PDF)</a></li>
						</ul>
						<li><%= link_to "Projects", projects_path %></li>
					</ul>
				</nav>
			</div>
		</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to my Website</h1>

	<h2>	
	Year 4: B.ASc in EngSci
	<br>
	Entrepreneur, The Next 36
	</h2>
	<br>
	<p style ="font-size: 0.9em; text-align: left">
		I am a fourth year Engineering Science student at the University of Toronto. Right now, I'm studying in the Electrical and Computer Engineering option.
		<br><br>
		My fields of interest are software, technology, and engineering design with an emphasis on Human-Computer Interaction!
	</p>
	<a href="https://www.nextcanada.com/next-36"><img src="the-next-36-logo_1.png"></a>
	<br><br>
	<%= link_to "See more about me",	interactive_resume_path %>

</div>

app/views/static_pages/interactive_resume.html.erb
<div id="header">
    <h1 id="title">Alan Daniels</h1>
    <hr>
</div>

<button id="begin-button" class="btn btn-danger btn-large" onclick="bsod()">Begin!</button>

<img id="BSOD" src="BSOD.png"/>

<div id="one">
  <h1>
    <a href="#/" id="toggle-triangle-one" class="toggle-title toggle-triangle" onclick="toggle1()">&#9650;</a>
    <a href="#/" class="toggle-title" onclick="toggle1()">Kernel-mode Driver Development Intern @ AMD</a>
  </h1>
  <div id="one-body">
  <p>
    Fixing <b>a lot</b> of those.
  </p>
  <hr>
  <h4>Summary</h4>
  <p>
    Writing code to handle some essential GPU tasks like flipping, initialization, register programming.  
  </p>
  <h4>Highlights</h4>
  <h3>Intern of the Year Nominee</h3>
  <h3>New Feature Developer</h3>
  <ul>
    <li>Designer and lead developer of an upcoming driver feature</li>
    <li>Market analysis (<b>read:</b> forum scraping)</li>
    <li><a href="https://technet.microsoft.com/en-us/sysinternals/bb963901.aspx">Technical research</a></li>
    <li>Testing/analysis with <a href="https://msdn.microsoft.com/en-us/windows/hardware/commercialize/test/wpt/windows-performance-analyzer">Windows Performance Analyzer</a></li>
  </ul>
  <h3>Beloved Mentor</h3>
  <h3>XDMA Software Developer</h3>
  <ul>
    <li>Expertise with AMD's CrossFire&trade; Direct Memory Access (XDMA)</li>
    <li>XDMA software architecture improvements</li>
    <li>Software lead for two new XDMA features</li>
  </ul>
  <h3>WGCD Debugging Challenge Winner</h3>
  <h3>Polaris Bring-up Engineer</h3>
  <ul>
    <li>Bring-up testing and development for RX480, RX470, RX460</li>
    <li>Multi-team bug fixing</li>
    <li>Kernel-mode software lead for two Polaris projects</li>
  </ul>
  <img src="RX480.jpg"/>
  <hr>  
  <p class="quote">
    "Highly dedicated engineer with a high degree of technical excellence"
  </p>
  <p class="quote">
    "Technical abilities well beyond those expected from an intern"
  </p>
  <p class="quote">
    "Wonderful initiative and a positive attitude"
  </p>
  <h7>
    Markham, ON
  </h7>
  <br>
  <h7>
    May 2015 – Aug 2016
  </h7>
  <hr>
</div>
</div>

<div id="two">
  <h1>
    <a href="#/" id="toggle-triangle-two" class="toggle-title toggle-triangle" onclick="toggle2()">&#9650;</a>
    <a href="#/" class="toggle-title" onclick="toggle2()">Hacker Academy</a>
  </h1>
  <div id="two-body">
  <p>
    Check us out at <a href="https://www.hackeracademy.org/">hackeracademy.org</a>
  </p>
  <div class="centered-image">
    <a href="https://www.hackeracademy.org/">
      <img src="HA Schedule.png"/>
    </a>
  </div>
  <hr>
  <h4>Summary</h4>
  <p>
    We're a group of students who are passionate about tech and software. We live by the hacker culture, which is all about promoting and practicing cleverness and creativity, having an inquisitive attitude, sharing knowledge, and hands-on learning. 
  <p>
  <h4>Highlights</h4>
  <h3>Event Organizer and Attendee</h3>
  <ul>
    <li>Weekly talks</li>
    <li>Monthly programming competitions</li>
    <li>Online challenges</li>
  </ul>
  <h3>Lead Web Developer</h3>
  <ul>
    <li>Designed and implemented the club website</li>
    <li>Support for users, events, achievements</li>
    <li>Over 200 registered accounts</li>
  </ul>
  <h3>Outreach</h3>
  <ul>
    <li>Advertised events using Facebook and MailChimp</li>
    <li>Developed a <a href="https://www.hackeracademy.org/Hacker%20Academy%20Sponsorship%20Package%202015.pdf">sponsorship package</a> and contacted various companies</li>
    <li>Poster design</li>
  </ul>
  <div class="centered-image">
    <img src="General HA Poster.png"/>
  </div>
  <hr>
  <h7>
    President 
    <br>
    Sept 2014 - Present 
  </h7>
  <br>
  <br>
  <h7>
    Member  
    <br>
    Sept 2012 – May 2014
  </h7>
  <hr>
</div>
</div>

<div id="three">
  <h1>
    <a href="#/" id="toggle-triangle-three" class="toggle-title toggle-triangle" onclick="toggle3()">&#9650;</a>
    <a href="#/" class="toggle-title" onclick="toggle3()">University of Toronto Engineering Design Projects</a>
  </h1>
  <div id="three-body">
  <p> 
    Check out my <%= link_to "Projects", projects_path %> for more details.
  </p>
  <hr>
  <h4>Summary</h4>
  <p>
    Problem analysis, engineering design, prototyping.  
  </p>
  <h4>Highlights</h4>
  <h3>AER201 - Flashlight Testing Machine</h3>
  <ul>
    <li>Worked with a team of three to build a complex machine</li>
    <li>Developed knowledge of electromechanical design, circuitry, and microprocessor functionality</li>
  </ul>

  <h3>UTEK - Designing a Personal Vehicle for Extreme Conditions</h3>
  <ul>
    <li>Produced a design prototype and product pitch in a team of four</li>
  </ul>
  <h3>ESC102 - Designing a Writing Utensil for Individuals with Parkinson's Disease</h3>
  <ul>
    <li>Developed a high-fidelity conceptual design and product pitch in a team of four</li>
    <li>Completed extensive community analysis and research</li>
    <li>Performed vast amounts of prototyping and implemented testing protocol</li>
  </ul>
  <hr>
</div>

<div id="four">
  <h1>
    <a href="#/" id="toggle-triangle-four" class="toggle-title toggle-triangle" onclick="toggle4()">&#9650;</a>
    <a href="#/" class="toggle-title" onclick="toggle4()">Software Projects</a>
  </h1>
  <div id="four-body">
  <p> 
    Check out my <%= link_to "Projects", projects_path %> for more details.
  </p>
  <hr>
  <h4>Summary</h4>
  <p>
    Some things I made in my spare time.
  </p>
  <h4>Highlights</h4>
  <h3>Shoot'em Up Game</h3>
  <ul>
    <li>Developed a scrolling shoot'em up game in Java, sprites provided by <a href="https://www.bigvikinggames.com/">Big Viking Games</a></li>
    <li>Play it on my <%= link_to "Projects", projects_path %>  page </li>
  </ul>
  <div class="centered-image">
    <img src="BVG Screenshot.png">
  </div>
  <h3>Hacktoberfest</h3>
  <ul>
    <li>Contributed to two open source projects as part of the <a href="https://hacktoberfest.digitalocean.com/">Hacktoberfest initiative</a></li>
    <li>Updated <a href="http://asciidoctor.org/">asciidoctor</a> parser logic and documentation</li>
    <li>Uploaded solutions to projects from <a href="http://www.theodinproject.com/">The Odin Project</a></li>
  </ul>
  <h3>Windows Phone 8 Hackathon</h3>
  <ul>
    <li>Developed a game (Gomoku) app for the Windows Phone 8 in a team of three</li>
  </ul>
  <h3>This Website &#9786;</h3>
</div>
</div>

app/views/static_pages/projects.html.erb
<% provide(:title, 'Projects') %>
<h1>Projects</h1>
<br>
<h2>Big Viking Scrolling Shoot'em Up</h2>
	<h3>Java Game</h3>
    <p style = "font-size: 1.1em; text-align: center">
    	 <a href="/BigVikingGame.jar" target="_blank">Download</a>
   	</p>
   	<!--<p style = "text-align: center">
    	 <%= link_to image_tag("bvggametitlescreen.png", alt: "Rails"), '/BigVikingGame.' %>
   	</p>-->
    <p style = "text-align: center">
      <applet codebase="" code="bvgapplet.MainScreenApplet" width="265" height="383"></applet>
    </p>
    <p style="text-align: right">Images provided courtesy of <a href="http://www.bigvikinggames.com/">Big Viking Games. </a>
    </p>
    <p style = "font-size: 0.9em;">
      <br>
      Applet may not display in some browsers. 
      <br>
      First run may pause to load at the beginnning. 
    </p>
<br>

<h2>AER201 Engineering Design</h2>
	<h3>
		Building a Flashlight Testing Machine</h3>
    <br><br>
    <p style = "font-size: 1.2em; text-align: left">
      <a href="/Team 7 - AER201 Final Report.pdf" target="_blank">Final Report</a>
      <br>
      • Worked with a team of three to build a complex machine <br>
      • Performed extensive unassisted research, survey, and problem solving <br>
      • Built strong group dynamics <br>
      • Developed knowledge of electromechanical design, circuitry, and microprocessor functionality <br>
      • Practiced professional organizational techniques such as Gantt charts and CPM
    </p>
    <br>
    <p style = "font-size: 1.2em; text-align: center">
       <img src="/IMG_0594.JPG" style="width:512px;height:384px"><br>
       Interior of the machine
    </p>
<br>
<br>

<h2>UTEK University of Toronto Engineering Kompetition</h2>
  <h3>Designing a Personal Vehicle for Extreme Conditions</h3>
    <br><br>
    <p style = "font-size: 1.2em; text-align: left">
      • Produced a design prototype and product pitch in a team of four
    </p>
    <br>
    <p style = "font-size: 1.2em; text-align: center">
      <img src="/IMG_0554.JPG" style="width:384px;height:512px">
      &nbsp&nbsp&nbsp
      <img src="/IMG_0555.JPG" style="width:384px;height:512px">
      <br>
      The initial paper prototype
      <br><br>
      <img src="/IMG_0556.JPG" style="width:384px;height:512px">
      <br>
      Added some design features to mitigate damage from falling objects
      <br><br>
      <img src="/IMG_0557.JPG" style="width:384px;height:512px">
      &nbsp&nbsp&nbsp
      <img src="/IMG_0558.JPG" style="width:384px;height:512px">
      <br>
      The final prototype<br>
      All sides withstood the impact of a brick falling 1m. It failed once we had a team member stand on it.<br> <br>
    </p>
    <p style = "font-size: 1.2em; text-align: left">
      <u>Design Features</u><br>
      • Slanted roof redirects debris off the car, increases aerodynamic wind flow, and has aesthetic appeal <br>
      • Tetrahedral passenger encasing protects driver in cases of extreme failure<br>
      • Inner bracing combats failure from side wall shear
    </p>
<br>
<br>

<h2>ESC102 Praxis II</h2>
	<h3>
		Designing a Writing Utensil for Individuals with Parkinson's Disease</h3>
    <br><br>
    <p style = "font-size: 1.2em; text-align: left">
      • Developed a high-fidelity conceptual design and product pitch in a team of four <br>
      • Completed extensive community analysis and research <br>
      • Exercised development of product metrics <br>
      • Performed vast amounts of prototyping and implemented testing protocol <br>
      • Communicated concept through showcase presentation and Q&A <br>
    </p>
    <p style = "text-align: center">
      <img src="/IMG_0333.JPG" style="width:384px;height:512px">
      &nbsp&nbsp&nbsp
      <img src="/IMG_0330.JPG" style="width:384px;height:512px"><br>
      Some early design ideas<br><br>
      <img src="/IMG_0317.JPG" style="width:384px;height:512px">
      &nbsp&nbsp&nbsp
      <img src="/IMG_0322.JPG" style="width:384px;height:512px">
      <br><br>
      <img src="/IMG_0327.JPG" style="width:384px;height:512px"><br>
      The evolution of the finger pen design<br><br>
      <img src="/IMG_0349.JPG" style="width:384px;height:512px">
      <br>
      One of our group members, Rio, at our booth<br><br>
      <img src="/IMG_0350.JPG" style="width:384px;height:512px"><br>
      The final design, the ball grip pen
    </p>
<br><br>
<h2>CIV102 Structures and Materials - An Introduction to Engineering Design</h2> 
  <h3>Building a Beam Bridge out of MatBoard</h3>
  <br><br>
  <p stlye = "text-align: left">
    • Perform research on beam bridge designs <br>
    • Used extensive excel spreadsheet and many formulae to optimize design dimensions <br>
    • Planned and constructed MatBoard beam bridge <br>
  </p>
  <p style = "text-align: center">
    <img src="/IMG_0302.JPG" style="width:384px;height:512px"><br>
    Marking the dimensions <br><br>
    <img src="/IMG_0305.JPG" style="width:384px;height:512px"><br>
    The final product
  </p>
	